BASE_URL = "https://tobeto.com/giris"
Login_xlsx = "data/Login.xlsx"
Register_xlsx = "data/register.xlsx"
EMPTYMESSAGE_XPATH_1 = "//*[@id='__next']/div/main/section/div/div/div[1]/div/form/p[1]"
EMPTYMESSAGE_XPATH_2 = "//*[@id='__next']/div/main/section/div/div/div[1]/div/form/p[2]"
EMPTYMESSAGE = "Doldurulması zorunlu alan*"
EMAIL_NAME = "email"
PASSWORD_NAME ="password"
LOGIN_BUTTON_XPATH ="//*[@id='__next']/div/main/section/div/div/div[1]/div/form/button"
VALID_LOGIN_XPATH = "//*[@id='__next']/div/div[2]/div/div[2]"
VALID_LOGIN = "• Giriş başarılı."
FIRSTNAME_NAME = "firstName"
LASTNAME_NAME = "lastName"
PASSWORDAGAIN_NAME = "passwordAgain"
PHONE_NUMBER_ID = "phoneNumber"
RECAPTCHA_XPATH = "//*[@id='recaptcha-anchor']/div[1]"
FINAL_REGISTER_XPATH = "/html/body/div[4]/div/div/div/div/div/div[3]/button[2]"
REGISTER = "Kayıt Ol"
REGISTER_XPATH = "//*[@id='__next']/div/main/section/div/div/div[1]/div/div/button"
CANT_REGISTER = "• Girdiğiniz e-posta adresi ile kayıtlı üyelik bulunmaktadır."
CANT_REGISTER_XPATH = "//*[@id='__next']/div/div[2]/div/div[2])"
INVALID_EMAIL_XPATH ="//*[@id='__next']/div/main/section/div/div/div[1]/div/div/form/p"
INVALID_EMAIL = "Geçersiz e-posta adresi*"